### ISSUE TITLE
ckeditor editable area height should depend on the height of its toolbar

### ISSUE THREAD

**Issue by dersugarciasanz** [webix-hub/components#14]
In the ckeditor initialization, the height of the editable area is hard-coded. 

https://github.com/webix-hub/components/blob/master/ckeditor/ckeditor.js#L24

`height:this.$height - 44`	

It works fine if the toolbar takes one line. However, if the toolbar takes more than one line, and you write on the editor to trigger the vertical scroll to appear, the toolbar hides behind its parent.

For example, if the toolbar takes two lines, the correct height would be this.$height - 77

**Comment by mkozhukh** [comment]
Updated, so now this values can be configured through barHeight property

```
webix.ui({ view:"ckeditor", barHeight: 55 })
```

This value can be adjusted according to your needs. 
Unfortunately, the editor doesn't provide any API to set the full height.
