### ISSUE TITLE
subtracting a hardcoded barHeight does not work when TinyMCE menubar is hidden

### ISSUE THREAD

**Issue by Doogiemuc** [webix-hub/components#21]
The height of tinyMCE depends on wether the tinyMCE menubar is shown. This has to be taken into account, when setting the inner size of the editor  in _set_inner_size() method.

https://github.com/webix-hub/components/blob/1b1cedf0c13f712a2232b1290cfb065dd208202b/tinymce/tinymce.js#L64

**Comment by mkozhukh** [comment]
barHeight can be configured in the widget's settings

```
webix.ui({ view:"tinymce-editor", barHeight: 55 })
```
This value can be adjusted according to your needs. 
Unfortunately, the editor doesn't provide any API to set the full height.
