### ISSUE TITLE
Highcharts integration

### ISSUE THREAD

**Issue by dandv** [webix-hub/components#25]
Probably the best open-source charting library out there

**Comment by dandv** [comment]
@HelgaListopad: what was the resolution? Thanks!

**Comment by HelgaListopad** [comment]
@dandv the initial version of integration is already available at
https://github.com/webix-hub/components/tree/master/highcharts

**Comment by dandv** [comment]
Great, thank you. Its helps to mention why an issue was closed, for those
who follow the issue in particular, but might not follow Webix general
development very closely.
