### ISSUE TITLE
Missing Icons in Example

### ISSUE THREAD

**Issue by bowersj** [webix-hub/components#31]
Hi Webix.

I found an [example](http://webix-hub.github.io/components/formeditor/sample.html) where the icons are not displaying and I just wanted to let you know.
Here is an image, ![example](https://user-images.githubusercontent.com/31971631/55653979-53e53600-57ad-11e9-898c-76d50c25c435.png)

I find myself using your product more and more every day, keep up the great work!

**Comment by HelgaListopad** [comment]
Hi @bowersj 

Thank you, this fix is already on Github and will be available at our CDN soon.
